### PR TITLE
Udp ports

### PR DESCRIPTION
**Pull request by xguerreropau**
gnss-sdr is now able to send the same monitor UDP packages to multiple ports

### CODE REVIEW

**Comment by carlesfernandez** [comment]
Thanks!

**Comment by jwmelto** [comment]
Shouldn't this change also have updated the sample configuration files? It is a breaking change for existing users. Another option would have been to leave the keyword unchanged, since existing single port configs would still work (maybe)

Don't get me wrong, I've wanted this change for years. I'm just trying to consider existing users.

**Comment by carlesfernandez** [comment]
Hi @jwmelto,

this change is not breaking any existing configuration, as far as I can see. The parameter name remains the same (`Monitor.udp_port`), and specifying a single port is still valid. Have I missed something?

**Comment by jwmelto** [comment]
You are right; the variable changed but not the config tag. I didn't read carefully. Thanks.

**Pull request merged**
