### PR TITLE
Fake multichannel

### PR DESCRIPTION
**Pull request by vladisslav2011**
Make it possible to receive multiple constellations using single channel wideband device (HackRF/LimeSDR/USRP).
Demonstration: https://www.youtube.com/watch?v=ZQs2sFchJ6w https://www.youtube.com/watch?v=HnZkKj9a-QM

### CODE REVIEW

**Comment by jwmelto** [comment]
Help me understand what this PR does, since the code change is trivial.

On [line 138](https://github.com/gnss-sdr/gnss-sdr/blob/476e1d28019e339d60fde382ebec59020e410916/src/core/receiver/gnss_flowgraph.cc#L138) the number of channels from the signal source are extracted (in your examples, this value is 3). Then the three signal conditioners are created.

Then, starting at line 933](https://github.com/gnss-sdr/gnss-sdr/blob/476e1d28019e339d60fde382ebec59020e410916/src/core/receiver/gnss_flowgraph.cc#L933), each channel of the output is connected to a corresponding signal conditioner.

As I work through this, what I'm guessing is that the signal source doesn't actually support multiple channels; and you are emulating the multi-channel capability by connecting different processing chains to the same source output. While this is a nice use of the underlying GNU Radio infrastructure, I'm less comfortable with your (under-documented) approach for GNSS-SDR.

Personally, I've butted up against the expressive limitations of the config file, and would like for more flexibility, but I'm not convinced (yet) that this is a good change to the baseline. The whole wiring of the the flowgraph is brittle and inflexible, beyond the pre-defined flexibility in this file. I'm wondering if embracing GNU Radio more closely (maybe even a GRC file) is a better solution to this issue?

**Comment by vladisslav2011** [comment]
This PR makes it possible to receive multiple constellations at different frequencies using one single channel device. This is achieved by connecting several signal conditioners to the same signal source/channel and setting different IF offsets.
It may be better to implement explicit signal conditioner connection specification by adding "SignalConditioner#.SignalSource=N" and "SignalConditioner#.SourceChannel=N" options, but this one line change does the trick and should not break anything.
The documentation may be updated to specify the order in which signal conditioners are connected to multiple single-channel devices when the specified number of channels exceeds actual number of device channels (1), but as this is done in the same order as with multiple real multichannel devices, I don't know, is it really required.

**Comment by mustafaefecetin** [comment]
What is your system configuration? Because I couldn't keep up with the 56MHz stream. My host configuration is,
--------------- 
OS: Ubuntu 20.04.5 LTS x86_64 
Host: HP Z4 G4 Workstation 
Kernel: 5.14.0-1056-oem 
Shell: bash 5.0.17 
CPU: Intel Xeon W-2123 (8) @ 3.900GH
GPU: NVIDIA Quadro P2000 
Memory: 2919MiB / 31835MiB DDR4 @2667MHz
--------------- 
I followed the guidline in -> 
[USRP Host Performance Tips&Tricks](https://kb.ettus.com/USRP_Host_Performance_Tuning_Tips_and_Tricks)
However overflow is still occuring. I am not sure volk is working properly. Although I run `volk_profile` and `volk_gnsssdr_profile`.

**Comment by vladisslav2011** [comment]
> What is your system configuration?
OS: Ubuntu 18.04.6 LTS x86_64
Kernel: 5.4.0-136-generic
CPU: AMD Ryzen 9 5950X 16-Core Processor
RAM: 64Gb DDR4

You may have to apply this patch: https://github.com/vladisslav2011/gr-osmosdr/commit/1888972533cb57dfa1ee0fa9f5e18fda06040a9b

You may try to reduce the sampling rate to 48MHz. It should be enough to get both BeiDou and Glonass.

**Comment by mustafaefecetin** [comment]
Thanks for your reply, @vladisslav2011 

I will try that ->
> You may have to apply this patch: [vladisslav2011/gr-osmosdr@1888972](https://github.com/vladisslav2011/gr-osmosdr/commit/1888972533cb57dfa1ee0fa9f5e18fda06040a9b)

I've tried the HackRF configuration and only keep up with 20MHz bw and 2 MHz internal_fs_sps. Also, I will try to run default configuration with more powerfull host which has 20 threads.

**Comment by aniljangral** [comment]
Hi I am trying to use the multichannel gnss receiver with hack rf... when I use the code, it says segmentation fault.. Can you help?

**Comment by vladisslav2011** [comment]
@aniljangral 
Current "next" should segfault with config files from this PR, so maybe you just forgot to run `cmake .. && make` after checkout...
Could you provide some more information:
1. Output from `git show`
2. Config file (if you have modified supplied gnss-sdr_multichannel_GPS_Galileo_Beidou_L1_hackrf_realtime.conf)
3. GNSS-SDR startup log
4. Stack trace from crash

**Comment by vladisslav2011** [comment]
I've rebased this PR on top of current 'next' branch (4836785baca6c36b98d74e1998d812e2734e4ce6) and corrected config files placement.
It still works very well at least on my machine - tracks 19 satellites and gives relatively good PVT.

**Comment by jwmelto** [comment]
@carlesfernandez what are your thoughts? This is a trivial change that doesn't seem to do harm, and has been around for a while.

**Comment by aniljangral** [comment]
Thank you for your prompt reply!
I have rebuilt the gnss-sdr PR and tested it with the my-first-GNSS-SDR-receiver.conf file. it works well! 
However, when I connect my USRP b205mini SDR, It again gives the segfault. 
I am attaching the screenshot of the error and the configuration file that I have used(changed the device addr). 
I am also attaching the screenshot of the git show.
Rest, I have built the PR on an old machine and my MacBook Air M2. I get the same result.
The config are:-
(Old machine)- intel i3, 4 GBDDR, ubuntu 22.04.3
Macbook- M2chip, 8GB, Ubuntu 23.10-live-server(VM in UTM hypervisor)
SDR :- USRP B205mini
            HackRFone

I am not very good at computers.. Please bear with me!!
I need help to complete this PR. If you can, please give me the direct link to the conf files for accessing GPS, Gallelio, Beidou, and GLONAS using USRP b205mini and hackrfone. 
Also, do I need to build the PR for visuals (those flashy screens) separately on my machine for system wide accessibility or I need to build it inside the GNSS-SDR PR to work?
IMG_7720
IMG_7721
IMG_7722
IMG_7721
IMG_7720
IMG_7722

**Comment by vladisslav2011** [comment]
@aniljangral 
Your screenshots are showing, that you have built the "next" branch instead of this PR...
How to build this PR (assuming, that you have cloned GNSS-SDR into "gnss-sdr" dir):
```
cd gnss-sdr
git fetch https://github.com/vladisslav2011/gnss-sdr
git checkout FETCH_HEAD -b fake_multichannel
cd build
cmake ..
make -j9
```

**Comment by vladisslav2011** [comment]
@aniljangral 
I've updated my latest comment. I forgot to add a branch to the fetch cmd.

**Comment by aniljangral** [comment]
Hi
Thanks you for the help!
I followed the steps given by you and build the PR branch successfully. I am attaching the git show result.
 Post that, I I tried to search for any conf file for receiving GPS, Gallelio, Bediou and Glonass using USRP/ HackRF in the conf folder, which I did not find.
Anyways, I tried to use a **"gnss-sdr_GPS_L1_USRP_realtime.conf"** file, which started but could not give me result. I could observe that it would try to "Lock on to a particular channel", but could not do so! 
It says **"Loss of Lock in Channel 1!**...  Screenshot is attached.
Further in one of the time, it would also say **"7 overflows occurred"**... Screenshot attached.
I presume that the receiver is trying to lock onto a GPS channel which it is not able to hold on to! I would add here that I have tried using two different antennas, both are off the market type antennae purchased from amazon. Photos of the both are attached.
I have also attached a photo of the actual **SDR b205 mini** that I am using.
Please help! I request you to help me understand the issue and resolve it. I also urge you to please give me a link to the **conf files for accessing GPS, Gallelio, Beidou, and GLONAS using USRP b205mini and hackrfone.**!

Thanks!

[IMG_7733](https://github.com/gnss-sdr/gnss-sdr/assets/141207416/5e4319e8-b6f2-45e4-b4de-994b09e84134)
IMG_7726
IMG_7724
IMG_7727
IMG_7730
IMG_7732

**Comment by vladisslav2011** [comment]
Hmmm...
You are still running GNSS-SDR built from the "next" branch (f80c5373b), that does not support "fake multichannel".
This PR commit id is b5b1d14.

"7 overflows occurred" means that your machine is not powerful enough to process full bandwidth or buffers are too small.

b205 will not work with this antenna ("GPS Antenna 1575.42MHz"). It needs an external bias tee and 3.3V power supply.
The second antenna does not cover the required band and has wrong polarization (linear instead of RHCP), so it would not work too.
Sorry for mistakes. I'm being constantly disturbed while writing comments here...

**Comment by aniljangral** [comment]
Hi
By mistake I posted yesterday's screenshot! I have completed the PR build as you had told. The actual screenshot is attached now.
I'l try to increase the RAM of my machine, if it would help.
As for the antenna, its polarisation and the bias tee + power supply, I will try to find one in the lab as soon as possible. 
In the mean time, what about the conf files for accessing GPS, Gallelio, Beidou, and GLONAS (in a single multichannel receiver) using USRP b205mini and hackrfone? I couldn't find them anywhere now.
Thanks!
IMG_7733

**Comment by aniljangral** [comment]
Would any  of this antenna work? It says RHCP. I understand that I need bias tee + power supply for them.

**Comment by aniljangral** [comment]
Would any of this antenna work? It says RHCP. I understand that I need bias tee + power supply for them.
IMG_7734

**Comment by vladisslav2011** [comment]
Adding more will not help. Try increasing `num_recv_frames` to 512 or more and patching gr_osmosdr.
But nothing will help if your CPU is too slow to handle ~40 tracking channels @ 8..10Msps + at least one acquisition channel.
This antenna should work.
It looks like example config files were lost during rebase.
I've updated the PR. The examples should be here again.

**Comment by aniljangral** [comment]
Okay. 
The patching of gr_osmosdr means installing it system wide or do I install inside gnss-sdr directory?
I am trying to get hold of a more powerful machine.

**Comment by vladisslav2011** [comment]
There is no need to install patched gr_osmosdr anywhere.
Just point `ld-linux.so` to it by defining the `LD_PRELOAD` environment variable:
```
LD_PRELOAD='your path to gr_osmosdr build dir'/lib/libgnuradio-osmosdr.so gnss-sdr -c 'your config file'
```
There is no need to install the development version of GNSS-SDR as well. It can be easily run from it's build directory too.

**Comment by aniljangral** [comment]
Hiya
Based on our discussion, I have upgraded my system. In fact I have used a new system with i7 processor 23rd gen, 16 GB RAM, ubuntu 20.04.
Also I have added a bias tee to the antenna system.
I have rebuild the gnss-sdr project and built the fake_multichannel branch succesfully.
But, finally when I attempted to run my first gps receiver.conf file,  it gave me a ABI mismatch for UHD 4.6 against UHD 3.15. help me as I could install 3.15 as it seems to be discontinued or something! 
IMG_7779
IMG_7780

**Comment by vladisslav2011** [comment]
That's not a bias tee. That's an amplifier...
A bias tee consists of 2..3 parts: one inductor and 1..2 capacitors.

Rebuild gr-uhd or uninstall UHD 4.6 and install UHD 3.15 and matching firmware and FPGA images.

**Comment by aniljangral** [comment]
See, as to best of my understanding, Bias Tee is required to power the LNA present inside the active antenna(antenna + LNA).. so, when i use an external LNA with the normal antenna and power the LNA with an external DC source, it essentially makes an active antenna. Hence, it obviates the requirement of a bias tee.. correct me if I am wrong..

**Comment by vladisslav2011** [comment]
Your antenna is active, so it has an LNA inside. This LNA, when not powered, will add ~20...30db insertion loss, so the antenna will not work even with an external LNA. You may disassemble the antenna, remove the internal LNA and matching network and use an external LNA, but the external LNA should be put as close to the antenna as possible especially when the cable is not good at 1+GHz like this long thin RG174, that is usually used with these antennas.
It should be possible to test the setup using generic SDR software like SDR++, Gqrx, etc: tune to 1575.42 MHz, set the FFT size to 128k, FFT rate to 0.1s, zoom the spectrum/waterfall in and the narrowband signal components should become visible like here: https://www.youtube.com/watch?v=A9a5G or here https://www.youtube.com/watch?v=d1q4v7wB5zc

**Comment by carlesfernandez** [comment]
Not sure if this is the best solution (I think it is not), but let's accept this PR since it *seems* harmless.

**Comment by aniljangral** [comment]
Very well explained. Thanks then I will have to purchase a bias tee and may take a weeks time at least to be delivered.
One more help required, I do not have the data sheet for my active antenna, and we can see it is written on that GPS antenna and the center frequency as 1575.42MHz.. so, will it be good enough for receiving Gallelio, Beidou and GLONASS as well? Or, do I need to buy an active multi band GNSS antenna which specifies that it has capability to receive all GNSS signals?

**Comment by aniljangral** [comment]
Since the fake_multichannel branch has been merged with _next_ branch, do I need to build the next branch again??

**Comment by vladisslav2011** [comment]
Yes.

**Comment by lebougre2** [comment]
Hi ! 
I have a problem with this...
After 14 Hours, I don't receive any message. I use hackrf with your config file.
Can you help me ? 
Thanks

**Comment by aniljangral** [comment]
IMG_7780
I have rebuilt the next branch but however the UHD has issues with drivers. 
I built the gr-uhd with 3.15 version, then the config file still doesn't,t run. it fails in the Signal_source_block.
I presume some issues with the dependencies post merger, Please help.

**Comment by vladisslav2011** [comment]
@lebougre2 
It should give a PVT in 40...60 seconds, so something is wrong with your setup.
Does your setup work with non-multichannel configuration files?
Could you post a startup log (~20 first lines).

@aniljangral 

It still tries to use UHD 4.6, so pointing it to UHD 3.15 with `LD_PRELOAD` may work.

**Comment by lebougre2** [comment]
Yes my setup work good with GPS L1 C/A


Initializing GNSS-SDR v0.0.19.git-fake_multichannel-6731d1cb3 ... Please wait.
Logging will be written at "/tmp"
Use gnss-sdr --log_dir=/path/to/log to change that.
OsmoSdr arguments: hackrf=0,bias=1,buffers=256
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.10.9.2
built-in source types: file fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp xtrx 
Using HackRF One with firmware 2024.02.1
Using 256 buffers of size 262144.
Actual RX Rate: 2e+07 [SPS]...
Actual RX Freq: 1.56742e+09 [Hz]...
PLL Frequency tune error: 0 [Hz]...
Actual RX Gain: 0 dB...
Actual Bandwidth: 1.5e+07 [Hz]...
RF Channels: 2
Starting a TCP/IP server of RTCM messages on port 2101
The TCP/IP server of RTCM messages is up and running. Accepting connections ...
Tracking of GPS L1 C/A signal started on channel 6 for satellite GPS PRN 07 (Block IIR-M)
Tracking of GPS L1 C/A signal started on channel 1 for satellite GPS PRN 02 (Block IIR)
Current receiver time: 1 s
Tracking of GPS L1 C/A signal started on channel 8 for satellite GPS PRN 21 (Block IIR)
Tracking of Galileo E1C signal started on channel 11 for satellite Galileo PRN E25 (Block FOC-FM16)
Tracking of Beidou B1I signal started on channel 20 for satellite Beidou PRN 26 (Block BeiDou-3 MEO12)
Tracking of Beidou B1I signal started on channel 25 for satellite Beidou PRN 27 (Block BeiDou-3 3M3)
Tracking of Galileo E1C signal started on channel 15 for satellite Galileo PRN E36 (Block FOC-FM19)
Tracking of Beidou B1I signal started on channel 22 for satellite Beidou PRN 35 (Block BeiDou-3 MEO16)
Tracking of Galileo E1C signal started on channel 18 for satellite Galileo PRN E02 (Block FOC-FM11)
Tracking of Beidou B1I signal started on channel 24 for satellite Beidou PRN 45 (Block BeiDou-3 MEO23)
Tracking of Beidou B1I signal started on channel 30 for satellite Beidou PRN 53 (Block Unknown)
Tracking of Beidou B1I signal started on channel 23 for satellite Beidou PRN 23 (Block BeiDou-3 MEO05)
Tracking of GPS L1 C/A signal started on channel 2 for satellite GPS PRN 08 (Block IIF)
Tracking of Beidou B1I signal started on channel 32 for satellite Beidou PRN 25 (Block BeiDou-3 MEO11)
Current receiver time: 2 s
OOOOOOOOOOOOOTracking of Beidou B1I signal started on channel 21 for satellite Beidou PRN 03 (Block BeiDou-2 GEO07)
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOTracking of Beidou B1I signal started on channel 28 for satellite Beidou PRN 41 (Block BeiDou-3 MEO19)
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOTracking of Beidou B1I signal started on channel 29 for satellite Beidou PRN 33 (Block BeiDou-3 MEO14)
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOTracking of Beidou B1I signal started on channel 33 for satellite Beidou PRN 18 (Block BeiDou-3 GEOG8)
OOOOOOOOOOOOOOOOCurrent receiver time: 3 s
OOOOOOOOOOOOOOOOOOOO^XOOOOOOOOOOOOOOOOOOOOOOOOOOO^CStopping GNSS-SDR, please wait!
Stopping TCP/IP server on port 2101
Total GNSS-SDR run time: 6.01045 [seconds]
GNSS-SDR program ended.

**Comment by vladisslav2011** [comment]
@lebougre2 

> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOTracking of Beidou B1I signal started 

Your machine is too slow. Reduce the total number of tracking channels or record 10..15 minute IQ file with `hackrf_transfer` and process it offline.

**Comment by lebougre2** [comment]
How do you change the number of tracking channels ? with Channels.in_acquisition ?

**Comment by vladisslav2011** [comment]
10 channels in acquisition may be too many even for my laptop.
Try setting `Channels.in_acquisition` to 1. If it will still lose samples, reduce tracking channels to 6:
```
Channels_1B.count=6
Channels_1C.count=6
Channels_B1.count=6
Channels.in_acquisition=1
```

**Comment by lebougre2** [comment]
Its working ! Thank you a lot !

**Pull request merged**
