### PR TITLE
Fix normalization in dll_nc_e_minus_l_normalized

### PR DESCRIPTION
**Pull request by odrisci**
Fix for #333 - this does not change the default behaviour but adds an interface to the dll_nc_e_minus_l_normalized discriminator so that it can be correctly normalized for any correlation function and correlator spacing.

### CODE REVIEW

**Comment by carlesfernandez** [comment]
I'm testing this change in the `odrisci-fix_discriminator_normalization` branch, after appling those new parameters in the tracking loops (see commit 970fb6f8482671eed3e2c5c196a16b2359f849d4)

**Comment by odrisci** [comment]
Thanks Carles. I probably should have done that!

**Comment by odrisci** [comment]
I've just pushed a commit incorporating your additions and adding a unit test.

In the process I've realised that the normalization has some problems, so please hold off on merging!

The problem is this: the normalization assumes that the correlation function can be approximated by a straight line with a slope and spacing with an intercept on the y-axis of 1 when the tracking error is zero. The problem is that the y-intercept is not 1 in general, but only for the first and last linear segments of a BOC correlation function (and always for BPSK). So we need to add another parameter to the normalization: the y-intercept, which should default to 1.

I'm working on this too.

**Comment by carlesfernandez** [comment]
I've merged this branch and [odrisci:update_tracking](/odrisci/gnss-sdr/tree/update_tracking) into [gnss-sdr:odrisci-fix_discriminator_normalization](/gnss-sdr/gnss-sdr/tree/odrisci-fix_discriminator_normalization), including the latest additions to next.

I'm starting testing from there.

**Comment by carlesfernandez** [comment]
See #333

**Pull request closed without merging**
