### PR TITLE
Added Acquisition Files

### PR DESCRIPTION
**Pull request by piyush0411**
Added first acquisition files (PCPS based) for Galileo E5b signal.

### CODE REVIEW

**Comment by piyush0411** [comment]
I will add more acquisition files (similar to those for Galileo E5a signal) to this pull request in the coming days.

**Comment by carlesfernandez** [comment]
Dear @piyush0411 ,

you need to include your new files at src/algorithms/acquisition/adapters/CMakeLists.txt

Without that, the compiler won't compile them, so the block factory can't find their symbols.

**Comment by piyush0411** [comment]
@carlesfernandez Thanks Sir for the help.
Should I also add the Acquisition files for FPGA into that. Currently it contains only normal PCPS files but when I run cmake with FPGA enabled, it again throws a similar error.
So should I add them too there?

**Comment by piyush0411** [comment]
@carlesfernandez 
Sir should clang-format be applied to `CMakeLists.txt` too? Because it is disorienting the file completely.

**Comment by piyush0411** [comment]
@carlesfernandez 
How can I pass this clang-tidy check?
It is also not showing any details regarding why the check is failing.

**Comment by carlesfernandez** [comment]
@piyush0411  The failure of the clang-tidy check was not your fault. I re-run the job and it has now passed. Sometimes, jobs fail without an apparent cause.

**Comment by piyush0411** [comment]
@carlesfernandez Thanks sir.
Can you please explain how should I apply clang-tidy in my local machine.
I run the commands given in the `Coding Style` documentation but it always throws the following error

```-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:18 (project):
  The CMAKE_C_COMPILER:

    /usr/bin/clang

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/piyush/gnss-sdr/build/CMakeFiles/CMakeOutput.log".
See also "/home/piyush/gnss-sdr/build/CMakeFiles/CMakeError.log".
```

And now the normal `cmake ..` is also showing the same error.
Please help me solve this issue.

**Comment by carlesfernandez** [comment]
You need to install the clang compiler. In Ubuntu:

```
$ sudo apt-get install clang clang-tidy
```

**Comment by piyush0411** [comment]
@carlesfernandez 
The project is still not getting built sir. It is giving the following error

```
  CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot copy file
  "/home/piyush/gnss-sdr/build/volk_gnsssdr_module/build/volk_gnsssdr.pc" to
  "/usr/local/lib/pkgconfig/volk_gnsssdr.pc".


Makefile:128: recipe for target 'install' failed
make[3]: *** [install] Error 1
CMakeFiles/volk_gnsssdr_module.dir/build.make:73: recipe for target 'volk_gnsssdr_module/src/volk_gnsssdr_module-stamp/volk_gnsssdr_module-install' failed
make[2]: *** [volk_gnsssdr_module/src/volk_gnsssdr_module-stamp/volk_gnsssdr_module-install] Error 2
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/volk_gnsssdr_module.dir/all' failed
make[1]: *** [CMakeFiles/volk_gnsssdr_module.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

The `cmake_install.cmake` looks like the following

```
# Install script for directory: /home/piyush/gnss-sdr

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.  //line number 41
  include("/home/piyush/gnss-sdr/build/src/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/home/piyush/gnss-sdr/build/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
```

I am not able to identify the error.
I ran `$ cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \  -DCMAKE_C_COMPILER=/usr/bin/clang ..` followed by `make` on the terminal for building purpose.

Thanks 
Piyush

**Comment by carlesfernandez** [comment]
Are you compiling from scratch? Remember to delete all the content in your bulding directory before starting a building with a new compiler. After that, compile a few targets that clanf-tidy needs for a smooth compilation: 

```
$ cd gnss-sdr/build
$ rm -rf *
$ cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++  -DCMAKE_C_COMPILER=/usr/bin/clang ..
$ make volk_gnsssdr_module gtest-1.10.0 core_monitor pvt_libs
```

... and then you can run 

```
$ run-clang-tidy -fix
```

Hope this helps!

**Comment by piyush0411** [comment]
The `Galileo_E5b.h` file has been modified because the initial one was giving error due to redefining of variables. The `Galileo_E1.h` has been included so that I/NAV message signal parameters can be derived from it.

**Comment by piyush0411** [comment]
@carlesfernandez @luis-esteve 
The files for acquisition are ready now.
Kindly review them :)

Regards
Piyush

**Comment by piyush0411** [comment]
Hello Sir
I am getting the following warning while running unit-test for acquisition of the signal
```gr::buffer::allocate_buffer: warning: tried to allocate
   4 items of size 32000. Due to alignment requirements
   16 were allocated.  If this isn't OK, consider padding
   your structure to a power-of-two bytes.
   On this platform, our allocation granularity is 4096 bytes
```

What does this mean? Does it have anything to do with the parameter values?
All the files I have modified or created are present in this pull request.
Please help.

Thanks 
Piyush

**Comment by carlesfernandez** [comment]
Hi @piyush0411 ,

I've made some changes in the block factory that got in conflict with your changes. I've pushed a commit that hopefully fixes them.

**Comment by carlesfernandez** [comment]
@piyush0411 ,

about your question about the alignment requirements message, I'm quoting an answer by Marcus Muller in the GNU Radio mailing list some time ago:

```
So, GNU Radio's buffers look a lot like real circular buffers to the blocks using them:
For example, assume your buffer between source block A and sink block B is large enough to store
exactly 10000 of your items:
A-->B
Now, A has produced 9000 items, of which B has already consumed 8000. Your buffer thus looks
like this:

- - - - - - - - R W -

With R being the current position of the read pointer, i.e. the address of the first input item of the
next B::work() call, and W being the write pointer, i.e. the address of the first output_item on the
next A::work() call.
Each "- " (or "R " or "W ") is 1000 items worth of storage.

Now, we can agree that in this buffer, there are thousand items that must not be overwritten by the
next A::work call, and 9000 items space for new items.

What GNU Radio does is employ memory mapping magic to allow A to simply write contigously the
next 9000 items; to the process, the memory looks like this:

- - - - - - - - R W -|- - - - - - - - R W -

Notice that the second half is really just a transparent image of the first, being inserted there by the
memory control unit of your CPU.

Now, that is awesome on so many levels:
* it allows developers to always write their applications like the in- and output was just linear in
memory, no matter where in their buffer they are
* it allows full usage of the buffer, without having extra space allocated

Of course, this has an architectural downside:
On any fully-fledged general purpose CPU platform I know, you can only do this with pages; a page
is simply the smallest amount of memory you can tell your memory management unit to map
somewhere.
On Linux, these pages are generally 4KB. That's usually a bit handy, because it's a power of two
bytes, which means that the typical item sizes (1B for a byte/char, 2B for a short, 4B for a float or
int, and 8B for a std::complex<float> == gr_complex) fit well here, but not so cool if your item's size
is not a divider of 2**12. In that case, the scheduler has no chance but to find the smallest common
multiple of 4096 and your item size.

Greetings,
Marcus
```

In summary, it's safe to ignore this message, altough it indicates that there could be some performance hit.

**Comment by carlesfernandez** [comment]
Ups, it seems that I left an extra parenthesis here:
```
../src/core/receiver/gnss_block_factory.cc:622:32: error: expected ‘,’ or ‘;’ before ‘)’ token
         "Channel", "7X", queue));
                                ^
```

Could you please remove it and check that everything builds fine?

**Comment by piyush0411** [comment]
Sure, I shall do it.
One more question, how should I proceed with the unit-test then?

**Comment by piyush0411** [comment]
@carlesfernandez 
To merge this commit into my local system, how should I proceed?

**Comment by carlesfernandez** [comment]
Hi @piyush0411 ,

To merge this commit in your local repository:

```
$ git checkout Acquisition      <- go to your local Acquisition branch, if you are not already there
$ git pull origin Acquisition     <- pull from the Acquisition branch of your repository
```

Assuming that `origin` points to your repo https://github.com/piyush0411/gnss-sdr

For the testing, before having real-life signals, you can use the simple signal generator block, since you have already programmed the generation of E5b signals. You can get some inspiration from https://github.com/gnss-sdr/gnss-sdr/blob/next/src/tests/unit-tests/signal-processing-blocks/acquisition/galileo_e5a_pcps_acquisition_gsoc2014_gensource_test.cc

When adding your test, please remember to add it at src/tests/test_main.cc in order to get it compiled.

**Comment by piyush0411** [comment]
@carlesfernandez 
What does this error means?
```thread[thread-per-block[0]: <block signal_gen_cc (426)>]: basic_string::at: __n (which is 14) >= this->size() (which is 4)```

**Comment by carlesfernandez** [comment]
I guess you are getting a runtime error due to a misconfiguration or a bug in the signal_generation block.

**Comment by piyush0411** [comment]
Hello Sir
I am again getting the same error while running my test.
```[----------] 3 tests from GalileoE5bPcpsAcquisitionTest
[ RUN      ] GalileoE5bPcpsAcquisitionTest.Instantiate
[       OK ] GalileoE5bPcpsAcquisitionTest.Instantiate (3 ms)
[ RUN      ] GalileoE5bPcpsAcquisitionTest.ConnectAndRun
Processed 4000 samples in 250705 microseconds
[       OK ] GalileoE5bPcpsAcquisitionTest.ConnectAndRun (255 ms)
[ RUN      ] GalileoE5bPcpsAcquisitionTest.ValidationOfResults
gr::buffer::allocate_buffer: warning: tried to allocate
   4 items of size 32000. Due to alignment requirements
   16 were allocated.  If this isn't OK, consider padding
   your structure to a power-of-two bytes.
   On this platform, our allocation granularity is 4096 bytes.
```

My unit test is as follows
```/*!
 * \file Galileo_E5b_pcps_acquisition_test.cc
 * \brief  This class implements an acquisition test for
 * GalileoE5bPcpsAcquisition class based on some input parameters.
 * \author Piyush Gupta, 2020. piyush04111999@gmail.com
 * \note Code added as GSoC 2020 Program.
 *
 * -------------------------------------------------------------------------
 *
 * Copyright (C) 2010-2020  (see AUTHORS file for a list of contributors)
 *
 * GNSS-SDR is a software defined Global Navigation
 *          Satellite Systems receiver
 *
 * This file is part of GNSS-SDR.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * -------------------------------------------------------------------------
 */


#include "concurrent_queue.h"
#include "fir_filter.h"
#include "galileo_e5b_pcps_acquisition.h"
#include "gnss_block_factory.h"
#include "gnss_block_interface.h"
#include "gnss_sdr_valve.h"
#include "gnss_synchro.h"
#include "in_memory_configuration.h"
#include "pass_through.h"
#include "signal_generator.h"
#include "signal_generator_c.h"
#include <boost/make_shared.hpp>
#include <gnuradio/analog/sig_source_waveform.h>
#include <gnuradio/blocks/file_source.h>
#include <gnuradio/blocks/null_sink.h>
#include <gnuradio/top_block.h>
#include <gtest/gtest.h>
#include <pmt/pmt.h>
#include <chrono>
#include <cstdlib>
#include <utility>
#if HAS_GENERIC_LAMBDA
#else
#include <boost/bind.hpp>
#endif
#ifdef GR_GREATER_38
#include <gnuradio/analog/sig_source.h>
#else
#include <gnuradio/analog/sig_source_c.h>
#endif


// ######## GNURADIO BLOCK MESSAGE RECEVER #########
class GalileoE5bPcpsAcquisitionTest_msg_rx;

#if GNURADIO_USES_STD_POINTERS
using GalileoE5bPcpsAcquisitionTest_msg_rx_sptr = std::shared_ptr<GalileoE5bPcpsAcquisitionTest_msg_rx>;
#else
using GalileoE5bPcpsAcquisitionTest_msg_rx_sptr = boost::shared_ptr<GalileoE5bPcpsAcquisitionTest_msg_rx>;
#endif

GalileoE5bPcpsAcquisitionTest_msg_rx_sptr GalileoE5bPcpsAcquisitionTest_msg_rx_make();

class GalileoE5bPcpsAcquisitionTest_msg_rx : public gr::block
{
private:
    friend GalileoE5bPcpsAcquisitionTest_msg_rx_sptr GalileoE5bPcpsAcquisitionTest_msg_rx_make();
    void msg_handler_events(pmt::pmt_t msg);
    GalileoE5bPcpsAcquisitionTest_msg_rx();

public:
    int rx_message;
    ~GalileoE5bPcpsAcquisitionTest_msg_rx();  //!< Default destructor
};


GalileoE5bPcpsAcquisitionTest_msg_rx_sptr GalileoE5bPcpsAcquisitionTest_msg_rx_make()
{
    return GalileoE5bPcpsAcquisitionTest_msg_rx_sptr(new GalileoE5bPcpsAcquisitionTest_msg_rx());
}


void GalileoE5bPcpsAcquisitionTest_msg_rx::msg_handler_events(pmt::pmt_t msg)
{
    try
        {
            int64_t message = pmt::to_long(std::move(msg));
            rx_message = message;
        }
    catch (boost::bad_any_cast& e)
        {
            std::cout << "msg_handler_telemetry Bad any cast!" << std::endl;
            rx_message = 0;
        }
}


GalileoE5bPcpsAcquisitionTest_msg_rx::GalileoE5bPcpsAcquisitionTest_msg_rx() : gr::block("GalileoE5bPcpsAcquisitionTest_msg_rx", gr::io_signature::make(0, 0, 0), gr::io_signature::make(0, 0, 0))
{
    this->message_port_register_in(pmt::mp("events"));
    this->set_msg_handler(pmt::mp("events"),
#if HAS_GENERIC_LAMBDA
        [this](pmt::pmt_t&& PH1) { msg_handler_events(PH1); });
#else
#if BOOST_173_OR_GREATER
        boost::bind(&GalileoE5bPcpsAcquisitionTest_msg_rx::msg_handler_events, this, boost::placeholders::_1));
#else
        boost::bind(&GalileoE5bPcpsAcquisitionTest_msg_rx::msg_handler_events, this, _1));
#endif
#endif
    rx_message = 0;
}


GalileoE5bPcpsAcquisitionTest_msg_rx::~GalileoE5bPcpsAcquisitionTest_msg_rx() = default;


// ###########################################################

class GalileoE5bPcpsAcquisitionTest : public ::testing::Test
{
protected:
    GalileoE5bPcpsAcquisitionTest()
    {
        factory = std::make_shared<GNSSBlockFactory>();
        config = std::make_shared<InMemoryConfiguration>();
        item_size = sizeof(gr_complex);
        gnss_synchro = Gnss_Synchro();
    }

    ~GalileoE5bPcpsAcquisitionTest() = default;

    void init();

    gr::top_block_sptr top_block;
    std::shared_ptr<GNSSBlockFactory> factory;
    std::shared_ptr<InMemoryConfiguration> config;
    Gnss_Synchro gnss_synchro;
    size_t item_size;
};


void GalileoE5bPcpsAcquisitionTest::init()
{
    gnss_synchro.Channel_ID = 0;
    gnss_synchro.System = 'E';
    std::string signal = "7X";
    signal.copy(gnss_synchro.Signal, 2, 0);
    gnss_synchro.PRN = 1;
    config->set_property("GNSS-SDR.internal_fs_sps", "4000000");
    config->set_property("InputFilter.implementation", "Fir_Filter");
    config->set_property("InputFilter.input_item_type", "gr_complex");
    config->set_property("InputFilter.output_item_type", "gr_complex");
    config->set_property("InputFilter.taps_item_type", "float");
    config->set_property("InputFilter.number_of_taps", "11");
    config->set_property("InputFilter.number_of_bands", "2");
    config->set_property("InputFilter.band1_begin", "0.0");
    config->set_property("InputFilter.band1_end", "0.97");
    config->set_property("InputFilter.band2_begin", "0.98");
    config->set_property("InputFilter.band2_end", "1.0");
    config->set_property("InputFilter.ampl1_begin", "1.0");
    config->set_property("InputFilter.ampl1_end", "1.0");
    config->set_property("InputFilter.ampl2_begin", "0.0");
    config->set_property("InputFilter.ampl2_end", "0.0");
    config->set_property("InputFilter.band1_error", "1.0");
    config->set_property("InputFilter.band2_error", "1.0");
    config->set_property("InputFilter.filter_type", "bandpass");
    config->set_property("InputFilter.grid_density", "16");
    config->set_property("Acquisition_7X.item_type", "gr_complex");
    config->set_property("Acquisition_7X.coherent_integration_time_ms", "1");
    config->set_property("Acquisition_7X.dump", "true");
    config->set_property("Acquisition_7X.dump_filename", "./acquisition");
    config->set_property("Acquisition_7X.implementation", "Galileo_E5b_PCPS_Acquisition");
    config->set_property("Acquisition_7X.threshold", "0.001");
    config->set_property("Acquisition_7X.doppler_max", "10000");
    config->set_property("Acquisition_7X.doppler_step", "250");
    config->set_property("Acquisition_7X.repeat_satellite", "false");
}


TEST_F(GalileoE5bPcpsAcquisitionTest, Instantiate)
{
    init();
#if GNURADIO_USES_STD_POINTERS
    std::shared_ptr<GalileoE5bPcpsAcquisition> acquisition = std::make_shared<GalileoE5bPcpsAcquisition>(config.get(), "Acquisition_7X", 1, 0);
#else
    boost::shared_ptr<GalileoE5bPcpsAcquisition> acquisition = boost::make_shared<GalileoE5bPcpsAcquisition>(config.get(), "Acquisition_7X", 1, 0);
#endif
}


TEST_F(GalileoE5bPcpsAcquisitionTest, ConnectAndRun)
{
    int fs_in = 4000000;
    int nsamples = 4000;
    std::chrono::time_point<std::chrono::system_clock> begin, end;
    std::chrono::duration<double> elapsed_seconds(0);
    std::shared_ptr<Concurrent_Queue<pmt::pmt_t>> queue = std::make_shared<Concurrent_Queue<pmt::pmt_t>>();

    top_block = gr::make_top_block("Acquisition test");
    init();
#if GNURADIO_USES_STD_POINTERS
    std::shared_ptr<GalileoE5bPcpsAcquisition> acquisition = std::make_shared<GalileoE5bPcpsAcquisition>(config.get(), "Acquisition_7X", 1, 0);
#else
    boost::shared_ptr<GalileoE5bPcpsAcquisition> acquisition = boost::make_shared<GalileoE5bPcpsAcquisition>(config.get(), "Acquisition_7X", 1, 0);
#endif

    auto msg_rx = GalileoE5bPcpsAcquisitionTest_msg_rx_make();

    ASSERT_NO_THROW({
        acquisition->connect(top_block);
        auto source = gr::analog::sig_source_c::make(fs_in, gr::analog::GR_SIN_WAVE, 1000, 1, gr_complex(0));
        auto valve = gnss_sdr_make_valve(sizeof(gr_complex), nsamples, queue.get());
        top_block->connect(source, 0, valve, 0);
        top_block->connect(valve, 0, acquisition->get_left_block(), 0);
        top_block->msg_connect(acquisition->get_right_block(), pmt::mp("events"), msg_rx, pmt::mp("events"));
    }) << "Failure connecting the blocks of acquisition test.";

    EXPECT_NO_THROW({
        begin = std::chrono::system_clock::now();
        top_block->run();  // Start threads and wait
        end = std::chrono::system_clock::now();
        elapsed_seconds = end - begin;
    }) << "Failure running the top_block.";

    std::cout << "Processed " << nsamples << " samples in " << elapsed_seconds.count() * 1e6 << " microseconds" << std::endl;
}


TEST_F(GalileoE5bPcpsAcquisitionTest, ValidationOfResults)
{
    std::chrono::time_point<std::chrono::system_clock> begin, end;
    std::chrono::duration<double> elapsed_seconds(0);
    top_block = gr::make_top_block("Acquisition test");

    double expected_delay_samples = 2920;
    double expected_doppler_hz = -632;
    init();
    std::shared_ptr<GalileoE5bPcpsAcquisition> acquisition = std::make_shared<GalileoE5bPcpsAcquisition>(config.get(), "Acquisition_7X", 1, 0);
    std::shared_ptr<FirFilter> input_filter = std::make_shared<FirFilter>(config.get(), "InputFilter", 1, 1);
    auto msg_rx = GalileoE5bPcpsAcquisitionTest_msg_rx_make();
    std::shared_ptr<Concurrent_Queue<pmt::pmt_t>> queue = std::make_shared<Concurrent_Queue<pmt::pmt_t>>();

    ASSERT_NO_THROW({
        acquisition->set_channel(1);
    }) << "Failure setting channel.";

    ASSERT_NO_THROW({
        acquisition->set_gnss_synchro(&gnss_synchro);
    }) << "Failure setting gnss_synchro.";

    ASSERT_NO_THROW({
        acquisition->set_threshold(0.001);
    }) << "Failure setting threshold.";

    ASSERT_NO_THROW({
        acquisition->set_doppler_max(5000);
    }) << "Failure setting doppler_max.";

    ASSERT_NO_THROW({
        acquisition->set_doppler_step(100);
    }) << "Failure setting doppler_step.";

    ASSERT_NO_THROW({
        acquisition->connect(top_block);
    }) << "Failure connecting acquisition to the top_block.";

    acquisition->set_local_code();
    acquisition->set_state(1);  // Ensure that acquisition starts at the first sample
    acquisition->init();

    ASSERT_NO_THROW({
        std::shared_ptr<GNSSBlockInterface> signal_generator = std::make_shared<SignalGenerator>(config.get(), "SignalSource", 0, 1, queue.get());
        std::shared_ptr<GNSSBlockInterface> filter = std::make_shared<FirFilter>(config.get(), "InputFilter", 1, 1);
        std::shared_ptr<GNSSBlockInterface> signal_source = std::make_shared<GenSignalSource>(signal_generator, filter, "SignalSource", queue.get());
        filter->connect(top_block);
        signal_source->connect(top_block);
        top_block->connect(signal_source->get_right_block(), 0, acquisition->get_left_block(), 0);
        top_block->msg_connect(acquisition->get_right_block(), pmt::mp("events"), msg_rx, pmt::mp("events"));
    }) << "Failure connecting the blocks of acquisition test.";

    EXPECT_NO_THROW({
        begin = std::chrono::system_clock::now();
        top_block->run();  // Start threads and wait
        end = std::chrono::system_clock::now();
        elapsed_seconds = end - begin;
    }) << "Failure running the top_block.";

    uint64_t nsamples = gnss_synchro.Acq_samplestamp_samples;
    std::cout << "Acquired " << nsamples << " samples in " << elapsed_seconds.count() * 1e6 << " microseconds" << std::endl;

    ASSERT_EQ(1, msg_rx->rx_message) << "Acquisition failure. Expected message: 1=ACQ SUCCESS.";

    double delay_error_samples = std::abs(expected_delay_samples - gnss_synchro.Acq_delay_samples);
    float delay_error_chips = static_cast<float>(delay_error_samples) * 10230.0 / 4000.0;
    double doppler_error_hz = std::abs(expected_doppler_hz - gnss_synchro.Acq_doppler_hz);

    EXPECT_LE(doppler_error_hz, 666) << "Doppler error exceeds the expected value: 666 Hz = 2/(3*integration period)";
    EXPECT_LT(delay_error_chips, 0.5) << "Delay error exceeds the expected value: 0.5 chips";
}
```
Also, the tests are stopping after this warning.
Please help.

**Comment by carlesfernandez** [comment]
Dear @piyush0411 ,

I think you need to tell the signal generator to actually generate Galileo E5b signals. You need to include those parameters in your configuration, something like this:

```
config->set_property("SignalSource.item_type", "gr_complex");
config->set_property("SignalSource.num_satellites", "1");
config->set_property("SignalSource.system_0", "E");
config->set_property("SignalSource.signal_0", "7X");
config->set_property("SignalSource.PRN_0", "11");
config->set_property("SignalSource.CN0_dB_0", "50");
config->set_property("SignalSource.doppler_Hz_0", std::to_string(1000));
config->set_property("SignalSource.delay_chips_0", std::to_string(50));
config->set_property("SignalSource.delay_sec_0", std::to_string(94));
config->set_property("SignalSource.noise_flag", "false");
config->set_property("SignalSource.data_flag", "false");
config->set_property("SignalSource.BW_BB", "0.97");
config->set_property("SignalSource.dump", "false");
config->set_property("SignalSource.dump_filename", "../data/signal_source.dat");
```

Hope this helps!

**Comment by piyush0411** [comment]
@carlesfernandez Still not working sir,
Giving the following error
```[----------] 3 tests from GalileoE5bPcpsAcquisitionTest
[ RUN      ] GalileoE5bPcpsAcquisitionTest.Instantiate
[       OK ] GalileoE5bPcpsAcquisitionTest.Instantiate (5 ms)
[ RUN      ] GalileoE5bPcpsAcquisitionTest.ConnectAndRun
Processed 4000 samples in 250760 microseconds
[       OK ] GalileoE5bPcpsAcquisitionTest.ConnectAndRun (255 ms)
[ RUN      ] GalileoE5bPcpsAcquisitionTest.ValidationOfResults
gr::buffer::allocate_buffer: warning: tried to allocate
   4 items of size 32000. Due to alignment requirements
   16 were allocated.  If this isn't OK, consider padding
   your structure to a power-of-two bytes.
   On this platform, our allocation granularity is 4096 bytes.
thread[thread-per-block[0]: <block signal_gen_cc (427)>]: basic_string::at: __n (which is 14) >= this->size() (which is 4)
```

**Comment by piyush0411** [comment]
I have pushed the unit test here so that it can be reviewed by @luis-esteve  and @carlesfernandez   and the error can be identified. 
Thanks

**Comment by luis-esteve** [comment]
> I have pushed the unit test here so that it can be reviewed by @luis-esteve and @carlesfernandez and the error can be identified.
> Thanks

Hello Piyush, I've executed your code and run the test. I think the problem is that your test keeps running indefinitely. When you execute the top_block-> run () statement no one tells top_block when to stop.
You need to implement a message system like galileo_e5a_pcps_acquisition_gsoc2014_gensource_test.cc that manages the acquisition results

**Comment by carlesfernandez** [comment]
Hi @piyush0411 and @luis-esteve ,

I've been working on Piyush branch and I've got the acquisition test actually working. The result is at https://github.com/carlesfernandez/gnss-sdr/tree/piyush0411-Acquisition-fixed

Please test it by yourself:

```
git checkout Acquisition    <- or whatever your working branch is called
git pull https://github.com/carlesfernandez/gnss-sdr piyush0411-Acquisition-fixed
```

Please review it, and if you are fine with the changes please do again a PR, so we can move on.

Best regards,
Carles

**Comment by piyush0411** [comment]
@carlesfernandez ,
Hello Sir, I tried pulling the changes to my computer. However it is showing merge conflict. Also it is also pulling 371 extra commits to the repo. How should I proceed?

**Comment by carlesfernandez** [comment]
Hi @piyush0411 

just checkout your `Acquisition` branch and pull from there:

```
git checkout Acquisition
git pull https://github.com/carlesfernandez/gnss-sdr piyush0411-Acquisition-fixed
```

If there are conflicts, pick up the changes from the new branch and then commit the result:

```
git remote add cf https://github.com/carlesfernandez/gnss-sdr
git checkout cf/piyush0411-Acquisition-fixed  -- name-of-conflicting-file
```
 
changing `name-of-conflicting-file` by the actual file(s) with conflicts. After that just do:

```
git commit
```

to finalize the merge.

**Comment by luis-esteve** [comment]
Hi @piyush0411 and @carlesfernandez . I've downloaded the latest changes and I've tested it. This is the plot result from acquisition dump:
Galileo_E5b_results
It works fine. @piyush0411 you can do the PR.

**Pull request closed without merging**
