### PR TITLE
Fixed OS X building

### PR DESCRIPTION
**Pull request by rventura**
Minor changes to allow building on OS X.

### CODE REVIEW

**Comment by carlesfernandez** [comment]
Dear @rventura 

Building in MacOS X works well when using -DENABLE_UNIT_TESTING=ON. 

If you are getting errors in the building process, please open a new issue and provide details about the errors and the specific version you are working with.

Thanks,
Carles.

**Comment by rventura** [comment]
Building with unit testing fails because of lack of development files in OS X (at least when gtest is installed via homebrew). I'll open an issue on that.

Not however the fix in rtklib.h that was preventing compilation.

**Comment by carlesfernandez** [comment]
Mmmm now I'm realizing that you are using homebrew and I'm using Macports, that could be the reason why I'm not able to reproduce this issue. 

The problem with -DENABLE_UNIT_TESTING=ON could be related to the fact that GNSS-SDR uses the googletest sources (as recommended) instead of pre-built libraries. If you are not using googletest anywhere else, you can safely remove that package and GNSS-SDR's build system will download googletest source code for you if it is not detected in your system. Or simply doing `cmake -DENABLE_UNIT_TESTING=OFF ..`

**Comment by rventura** [comment]
You are absolutely right. I spotted today the problem. There was a gtest installation from a non-standard brew tap (ROS actually). I unlinked it and now gnss-sdr compile just fine (it downloads and builds googletests as expected).

**Pull request closed without merging**
