### PR TITLE
Added 'blocking' option to pcps_acquisition_cc

### PR DESCRIPTION
**Pull request by odrisci**
Using C++ 11 threading routines to create a worker thread that can
perform the FFT for acquisition in a non-blocking manner. By default
'blocking' is set to true, which is identical to the previous behaviour
(with the added overhead of an extra thread). When 'blocking' is set to
false, then the main thread does not wait for the worker, thereby
letting the receiver continue even when the FFT thread is working. This
is very useful for using FFT acquisition at higher sampling rates, where
the FFT cannot be performed in real-time.

The aim is to replace the separate pcps_multithread_acquisition_cc.

TODO: implement the same thing for the pcps_acquisition_sc

### CODE REVIEW

**Comment by carlesfernandez** [comment]
It works well in runtime, but tests `GpsL1CaPcpsAcquisitionTest.ValidationOfResults` and `GpsL2MPcpsAcquisitionTest.ValidationOfResults` fail. Other tests using the same block (such as `GpsL1CaPcpsAcquisitionGSoC2013Test.ValidationOfResults`) succeed, so maybe is a problem of the test. Looking into it.

**Comment by carlesfernandez** [comment]
Ok, I think I’ve got it.

It seems that the `blocking=false` option is not exactly non-blocking. This can be seen in  https://github.com/carlesfernandez/gnss-sdr/tree/odrisci-non_blocking_acq-test, where I did the following:

* Modified gps_l1_ca_pcps_acquisition_test.cc in order to wait for the Acquisition block to emit a message, and then stop the top_block. 
* Left galileo_e1_pcps_ambiguous_acquisition_test.cc as is (i.e., without any “waiting mechanism”)

The result is that, in my machine, `GpsL1CaPcpsAcquisitionTest` always passes but `GalileoE1PcpsAmbiguousAcquisitionTest` **sometimes passes, but sometimes it does not**.  In my interpretation, it just depends on how fast the acquisition_core thread returns the result message. The GNU Radio schedule just ask for more data, but the acq block is busy and let samples flow downstream. If the end of the data file is found before the acquisition block emits a message, the result is a `0` message (“Stop the receiver”) instant of `1` (“Positive Acquisition”).

This breaks the determinism provided by the GNU Radio schedule, since the result of the test depends on how fast the host machine performs the required signal processing. Even in the same machine, the test fails from time to time (!!).

I’m reluctant to merge the code as is into `next` because of this issue. Maybe it could be a new GNU Radio block `pcps_acquisition_non-blocking_cc.cc` called by the adapters according to the `blocking`  parameter. I’m willing to work on this, but I’m not sure if this would be the best way to go. 

Any other ideas on how to meet the GNU Radio schedule requirements with this approach?

**Comment by odrisci** [comment]
Ok. I see it now.  My logic is flawed.  I'll need to rework it a bit so that the calls to `send_positive_acquisition` etc occur in the worker thread. I'll work on it over the next few days and push an update. 

Thanks for your work on the tests.  I'll incorporate this into my update

**Comment by odrisci** [comment]
Ok, I've added some updates now - it passes the tests on my machine all the time now...

I haven't added a test for the case where `blocking=false`, we should probably add this before any potential merge. Also, I presume we would need to rebase from `next`.

Can you check that my updates work on your machine as well?

**Comment by carlesfernandez** [comment]
Ok, now it's working for me. I've moved to a branch called [`non_blocking_acq`](https://github.com/gnss-sdr/gnss-sdr/tree/non_blocking_acq) in the upstream repo. It's in sync with `next`, and I will push there any further commit to `next`, so it will be ready to merge when done. 

The increase in speed is awesome. Thanks for your contribution!

**Comment by carlesfernandez** [comment]
I'm closing this pull request, so we can continue the conversation in https://github.com/gnss-sdr/gnss-sdr/issues/69

**Pull request closed without merging**
